FROM pypy:3.9-7.3.11-slim-bookworm

WORKDIR /app
COPY . .

RUN pypy3 -m pip install -r requirements.txt
RUN pypy3 -m prisma generate
RUN apt-get update && apt-get install -y --no-install-recommends \
libuv1 \
zlib1g \
&& \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

EXPOSE 8080

CMD ["tail", "-f", "/dev/null"]

#docker build -t socketify_pypy3 --rm .
#docker run -tid --name=socketify_demo -v /src:/app -p 4000:8080 socketify_pypy3 sh -c "prisma db push --schema schema.prisma && pypy3 app.py --workers 4"
