FROM pypy:3.9-7.3.11-slim-bookworm

WORKDIR /app
COPY . .

RUN pypy3 -m pip install -r requirements.txt
RUN pypy3 -m prisma generate
RUN apt-get update && apt-get install -y --no-install-recommends \
libuv1 \
zlib1g \
&& \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

EXPOSE 8080

CMD ["tail", "-f", "/dev/null"]

#docker build -t robyn_demo --rm .
#docker run -tid --name=robyn_demo -v /src:/app -p 4000:8080 robyn_demo sh -c "prisma db push --schema /app/schema.prisma && pypy3 /app/app.py"
